### ISSUE TITLE
When will the training script for CLAD be made public?

### ISSUE THREAD

**Issue by YMLLG** [CLAD23/CLAD#1]
Following the ideas from the reference paper, I have not been able to reproduce the corresponding method. Therefore, may I ask when the training script for CLAD will be made public? Thank you.

**Comment by CLAD23** [comment]
Hi YMLLG,

Thank you for your interest in our work .

Our paper is currently under review. We plan to make the training script publicly available once the paper is accepted. We appreciate your patience and understanding during this process. If you have any other questions, please feel free to reach out.
